# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":email-relay"
    replace: "jw71noyk6@relay.firefox.com"

  - trigger: ":nifi"
    replace: "http://18.141.45.103:8080/nifi/"

  - trigger: ":fake-name"
    replace: "dummy kevin test {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%s"

  - trigger: ":zid"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d%H%M"

  - trigger: ":fake-email"
    replace: "kevin@dummy{{mydate}}.com"
    vars:
      - name: mydate
        type: date
        params:
          format: "%s"

  - trigger: ":fake-phone"
    replace: "123123123123"

  - trigger: ":fake-pass"
    replace: "123123123123"

  - trigger: ":jira-ticket"
    replace: "https://jurnal.atlassian.net/browse/ITG-"

  # Dates
  - trigger: ":now"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%A, %d %B %Y %r %Z"
      #
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%m-%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
