# Inserts a blank line between shell prompts
add_newline = true


# Replace the "❯" symbol in the prompt with "➜"
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)" 
# SPACESHIP_CHAR_SYMBOL="▲ "
