-- vim.cmd[[packadd catppuccino.nvim]]

-- local catppuccino = require("catppuccino")

-- -- configure it
-- catppuccino.setup(
--     {
--     colorscheme = "catppuccino",
--     transparency = false,
--     styles = {
--       comments = "italic",
--       functions = "italic",
--       keywords = "italic",
--       strings = "NONE",
--       variables = "NONE",
--     },
--     integrations = {
--       treesitter = true,
--       native_lsp = {
--         enabled = true,
--         styles = {
--           errors = "italic",
--           hints = "italic",
--           warnings = "italic",
--           information = "italic"
--         }
--       },
--       lsp_trouble = true,
--       lsp_saga = true,
--       gitgutter = false,
--       gitsigns = true,
--       telescope = true,
--       nvimtree = true,
--       which_key = false,
--       indent_blankline = false,
--       dashboard = false,
--       neogit = false,
--       vim_sneak = false,
--       fern = false,
--       barbar = false,
--       bufferline = false,
--       markdown = true,
--     }
--   }
-- )

-- -- load it
-- catppuccino.load()
